name: "Policy Tag"
description: "Tag policy image"
author: "Aserto Inc."
branding:
  icon: tag
  color: blue
inputs:
  source_tag:
    description: "source tag policy image"
    required: true
  target_tags:
    description: "one or more target image tags"
    required: true
  verbosity:
    description: "verbosity level [info|error|debug|trace]"
    required: true
    default: error
runs:
  using: docker
  image: 'docker://ghcr.io/opcr-io/policy:0.1'
  entrypoint: /app/tag.sh
